### ISSUE TITLE
A config file with constants is needed

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#103]
Para poder configurar el server fácilmente, sería genial tener un archivo config.js (o el nombre que quieran ponerle) en el que puedan especificarse los siguientes parámetros:
- Qué puerto(s) servir
- Si se sirve ssl, debería poder especificarse la dirección del key y del certificado firmado por la CA.
- Qué servidor de email utilizar. Si es smpt, un campo para el usuario, puerto, contraseña.

Si tienen algún otro comentario, pueden agregarlo y lo sumo.

**Comment by andresmanelli** [comment]
Creo que para el mail de activación se especifica el dominio de activación. Sería como el ex REMOTE pero para ese caso particular. También meterlo en ese archivo?

**Comment by fcladera** [comment]
On Thursday, March 24, 2016 3:33:05 PM ART, Andrés wrote:

> Creo que para el mail de activación se especifica el dominio de 
> activación. Sería como el ex REMOTE pero para ese caso 
> particular. También meterlo en ese archivo?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/103#issuecomment-200962071

Tienen que ser todos los parámetros del servidor de mail:
- Dirección (dominio)
- Puerto
- Usuario
- Contraseña
