### ISSUE TITLE
Email server

### ISSUE THREAD

**Issue by francoa** [MecatronicaUncu/Red-Social-Asociacion#113]
Aviso que cambié la contraseña porque era muy fácil e hubo tentativas de conexión desde San Pablo. Detalles por privado.

De todas formas la contraseña está literalmente escrita en el repo, así que por ahora sería bueno no subirla.

En fin, a lo que nos compete. Estuve leyendo sobre cómo hacer esto (http://arstechnica.com/information-technology/2014/02/how-to-run-your-own-e-mail-server-with-your-own-domain-part-1/) y parece que es bastante complicado. Estoy empezando a leer. Alguno tiene experiencia en este aspecto?

**Comment by francoa** [comment]
Y en cuanto a la falla que encontrabas Fer, se trata de una verificación adicional que pide Google. Algo así como un captcha que hay que poner para que registre la aplicación como segura.

**Comment by fcladera** [comment]
Sí, yo tengo mi propio servidor de email con postfix+dovecot (con DKIM, DMARC, SPF). Igual esto nunca se hace así. Los servidores de email son algo bastante frágil, y **NO** podemos crear un servidor de email para que nuestra aplicación quiera enviar emails.

Lo que se hace en general es configurar un servidor de mail externo (en un archivo de configuración del programa). Además, hay que crear una variable que sea

```
mailServedConfigured = true/false;
```

La parte de email no se puede testear automáticamente, hay que escribir un archivo de configuración usando un servidor específico para ver si funciona.

Igual, si probás que funciona la función/plugin que usás para mandar email una vez, y tenés la variable `mailServerConfigured`  una buena idea para probar es hacer un dump del body del mensaje que vas a enviar a la terminal, o a un archivo.

**Comment by francoa** [comment]
Ah yo había entendido por lo que habíamos hablado con el rulo que eso querías. Pero ahora que leo el mensaje del rulo el tampoco parecía muy seguro sobre qué era lo que querías jaajaj

**Comment by francoa** [comment]
Entonces, como para recapitular, me decís que podemos seguir usando el mismo servidor, sólo que configurándolo a través de algún archivo, algo así como lo que se discutía en #103

**Comment by fcladera** [comment]
Y ya a modo de comentario, no tiene nada que ver con el proyecto.
El artículo de ARS es bastante bueno si a alguien le interesa crear su propio servidor (for fun). Pero configurarlo es bastante complicado. 
Lo bueno es que aprendés como funciona el email por dentro, podés hacer cosas locas como filtrados de mail muy precisos, respuestas automáticas. Además, en teoría, es la mejor manera de escapar de que la NSA te lea los correos (claro, si tuvieras tu servidor de email en tu casa).
Lo malo es que lleva bastante tiempo configurarlo (calculo que el server completo fueron como 5 o 6 días de configuración). Y administrarlo, para que no te tomen como spammer, arreglar cuando alguien te toma como spammer, y arriesgarte a que tus emails no lleguen a destino.

**Comment by francoa** [comment]
Bueno, la última hora y media entonces me la pasé leyendo al pedo jaja

**Comment by fcladera** [comment]
En realidad tendría que haber en algún lado algo que sea parecido a esto 
![tutuploadsemail_settings](https://cloud.githubusercontent.com/assets/4083786/14161638/c4db3392-f6bb-11e5-8838-ad55403a8283.png)
Eso es un archivo de config de una app en php. Ahí especifica algunas variables útiles
- El autor del correo
- El servidor
- Como se conecta al servidor de mail? (TLS o "en crudo", lo mejor es que sea obligatoriamente TLS)
- El user del smtp
- El pass de smtp
- El host del smtp

**Comment by francoa** [comment]
o sea, decís que en vez de usar nodemailer desde `users.js` utilicemos alguno instalado directamente en el linux server (?)

**Comment by fcladera** [comment]
Por ejemplo, si yo quisiera configurar para usar gmail debería ser algo como

```
mailfrom = midireccion@gmail.com
fromName = EDT Fing - El mejor EDT del mercado
smtpUser = midireccion@gmail.com
smtppass = superContraseñaUltaSegura
smtphost = smtp.gmail.com
```

(aclaro que estos valores son a modo de ejemplo, dependerá del plugin que uses para enviar smtp (o si node lo trae nativo, de la función) los valores que hay que poner).

Obviamente, los valores del servidor de mail no tienen que estar en el repo, los configura el usuario antes de ir a producción.

**Comment by francoa** [comment]
ah ahi entendí

**Comment by fcladera** [comment]
No no! Si node ya tiene un nodemailer, usemos ese!

**Comment by fcladera** [comment]
Y lo último es que cuando escribís tu código para enviar un email, podrías tener una función wrapper de nodemailer que sea algo así (pseudo pseudo code haha)

```
mailerWrapper(string msg, string title, string direccion){
    if(mailServedConfigured)
        nodemailer(msg, title, direccion, ... otros parametros de config del server sacados del archivo de conf...);
    else
        // print a consola, a archivo de texto, a console.log()?
}
```

**Comment by francoa** [comment]
oka

**Comment by andresmanelli** [comment]
Pregunta, esto queda andando con #117 ? Porque lo que está online todavía no envía emails, pero por ahí es porque lo que está corriendo es viejo?

**Comment by francoa** [comment]
Y pasa lo mismo que antes. No va a funcionar online hasta demostrar con ese captcha que comentaba en otro issue que es una aplicación "segura". O que dejemos de usar gmail

**Comment by fcladera** [comment]
## Nunca vamos a poder hacer un deploy sin configurar mínimamente el servidor de email. Por eso yo insistía en que para pruebas, la función de email debería escribir el contenido del mensaje a console.log (por ejemplo), y no mandar el mensaje efectivamente. 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
