### ISSUE TITLE
Soporte para múltiples actividades en el mismo horario el calendario

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#119]
Mi idea era que si yo estoy suscripto a múltiples materias, todas las actividades se mostraran en un mismo calendario. Igual que el edt de la eni.
Actualmente no se muestra bien si trato de poner múltiples actividades en el mismo horario. En realidad, aparecen las actividades como "solapadas".
![dsa](https://cloud.githubusercontent.com/assets/4083786/14222763/0dde3a54-f84b-11e5-89df-b25be5d058d0.png)
una opción es que se haga más ancho la "fila" del día, y que las actividades se vayan poniendo una debajo de la otra. Otra opción es que el recuadro de actividades se haga más estrecho (verticalmente) para poner varias en el mismo día.

**Comment by andresmanelli** [comment]
Se puede plantear el problema genéricamente teniendo de entrada el número de filas disponibles y los inicios y finales de actividades y como salida la distribución de las mismas? Sería un golazo. U obtener el mínimo número de filas para tener un espaciado entre actividades "agradable a la vista".

**Comment by andresmanelli** [comment]
Pensé en una función recursiva que haga lo siguiente, partiendo de un array de actividades:
1. Elegir el nodo que comience antes (menor `a.ti`) -> Nodo `a0`
2. En un "arbol", crear hijos con los nodos compatibles con el elegido en el paso 1
   - Compatible <=> `a.ti > a0.tf || a.tf < a0.ti`
3. Para cada hijo, verifico compatibilidad (como el paso 2) entre este y los hermanos restantes "hacia la derecha".
   - Paso 3 recursivo para los niveles que se vayan creando
4. Calcular la [SVF](https://en.wikipedia.org/wiki/Volume_fraction) de las ramas así generadas y elegir la más compacta.
   - SVF = `( sum_duraciones(rama.nodos) ) / ( limits.tf - limits.ti )`
5. Llamar a la función (repetir desde 1) con un array que contenga los nodos no contenidos en la rama elegida hasta que todos estén contenidos en una rama.

Refernecias: 
- `a`: Nodo de actividad (fragmento de tiempo contiguo, si hacemos la fusión de actividades en un nodo según #131)
- `n.ti`: Tiempo de inicio
- `n.tf`: Tiempo de fin
- Cada rama sería una fila de un día.

Mañana si puedo hago un dibujito jaja.

**Comment by francoa** [comment]
Este no lo agarró nadie? @andresmanelli lo estás viendo en alguno de tus branches o lo tomo?

**Comment by andresmanelli** [comment]
No, no toque esto. Hice ese "algoritmo" nomas. Cero código.

-----Message d'origine-----
De : "Franco Ardiani" notifications@github.com
Envoyé : ‎16/‎04/‎2016 00:26
À : "MecatronicaUncu/Red-Social-Asociacion" Red-Social-Asociacion@noreply.github.com
Cc : "Andrés" andresmanelli@gmail.com
Objet : Re: [MecatronicaUncu/Red-Social-Asociacion] Soporte para múltiples actividades en el mismo horario el calendario (#119)

Este no lo agarró nadie? @andresmanelli lo estás viendo en alguno de tus branches o lo tomo?

**Comment by andresmanelli** [comment]
@francoa vi que hiciste un branch. te asigno asi no tocamos esto

**Comment by andresmanelli** [comment]
Anda muy bien pero no sé por qué me flashó esto:

![asd](https://cloud.githubusercontent.com/assets/7302217/15445744/30afa51a-1edc-11e6-9fe3-ae9b725d86b3.png)

voy a seguir probando.
