### ISSUE TITLE
Errror al crear una actividad fuera del horario permitido

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#122]
Creo que es una idea muy buena lo de tener un inicio y fin de actividades. Nos va a simplificar mucho la vida.

Encontré el siguiente problema: al crear una actividad nueva, si la hora de la actividad es > 22h, se muestra un mensaje de error pero la actividad se crea igual.
![eeras](https://cloud.githubusercontent.com/assets/4083786/14223087/1347c852-f850-11e5-91ee-b1963e701840.png)

**Comment by andresmanelli** [comment]
El problema está solucionado desde el frontend, pero podrían hacerse POSTs al server con otros horarios y se crearían igual. Entonces, hacemos una verificación desde el backend? O verificamos nuevamente antes de graficar que estén en regla los tiempos si es que se crearon actividades "raras"?

**Comment by fcladera** [comment]
On Tuesday, April 12, 2016 10:23:55 PM ART, Andrés wrote:

> El problema está solucionado desde el frontend, pero podrían 
> hacerse POSTs al server con otros horarios y se crearían igual. 
> Entonces, hacemos una verificación desde el backend? O 
> verificamos nuevamente antes de graficar que estén en regla los 
> tiempos si es que se crearon actividades "raras"?

Mmm, no creo que nadie esté haciendo posts on the wild, pero no está mal
hacer una verificación en el backend. Verificar antes de graficar no creo 
que
sea la solución. En teoría, si vos prohibís que se guarden estas cosas 
desde 
el frontend, y prevenís que hagan cosas raras con el backend, no debería
pasar más.
