### ISSUE TITLE
Cambiar nombre de unit test de jasmine

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#126]
Es un detalle nomás pero habría que poner algo como "unit" donde dice "your_target" en `Gruntfile.js`, línea 330

**Comment by francoa** [comment]
Este issue es de hincha pija culiao. Está bien que me revisen el código
pero ni en asf me controlaban tanto! xd

El Lun 04/04/2016, 22:49, Andrés notifications@github.com escribió:

> Assigned #126
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/126 to
> @francoa https://github.com/francoa.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/126#event-614529949
> 
> ## 

Franco Ardiani
Mechatronics Engineer

Sent from my mobile. Please excuse brevity.
