### ISSUE TITLE
Usar config.js en archivos de carpeta Datasets

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#140]
- regEdtNodes.js
- regUsers.js
- usersRel.js

De esta manera sólo se modifica `config.js` y el repo queda más limpio luego de `config`.

**Comment by fcladera** [comment]
Está buena la idea. Igual yo había pensado cambiar para que neo4j no se instale en una carpeta con el número de versión, sino algo genérico (como `server/bin/neo4j-files`). De esa manera no hay que cambiar el número de versión en todos los datasets.

**Comment by andresmanelli** [comment]
Pero esto es sobre el uso del usr y pass para conectarse al server de Neo4J. No sé si se me está pasando otra cosa.

**Comment by fcladera** [comment]
No, está bien lo que decís! Así limpiaríamos un poco el script config. 

Lo que yo digo es porque los scripts de los datasets necesitan conocer la ubicación de neo4j.

**Comment by andresmanelli** [comment]
Oka, entiendo. Lo dejo para otro issue por ahora. En un ratito mando PR para esta parte.
