### ISSUE TITLE
Certificado SSL self signed

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#15]
Como mecatronicauncu.org tiene implementado HTTP Strict Transport Security (HSTS) para subdominios, edt.mecatronicauncu.org va a devolver siempre un error ya que el certificado no está firmado por una CA. Si tienen su certificado gratis, pueden usarlo para esta ocasión.

**Comment by andresmanelli** [comment]
@fcladera , esto lo abriste para tener un certificado self signed o por el hecho de tenerlo? i.e, para que paguemos uno en serio? jaja. Si es por lo primero, este issue debería estar cerrado ya.

**Comment by fcladera** [comment]
El problema de esto es que estábamos tratando de hacer una demo en edt.mecatronicauncu.org y necesitábamos un certificado posta. Supongo que se puede cerrar, y cuando hagamos nuestra demo creamos un certificado.

**Comment by andresmanelli** [comment]
Cerrado, porque ya se genera el self signed. En algun momento si queremos hacer un deploy estable, habrá que poner platita para uno de verdad.
