### ISSUE TITLE
Agregar checkboxes en los favoritos para mezclar calendarios.

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#16]

**Comment by fcladera** [comment]
Si entiendo bien, esta es la de que varios calendarios se puedan "fusionar" en uno sólo. Creo incluso que debería ser por defecto, si uno está suscripto.

**Comment by andresmanelli** [comment]
Voy a ir pensando esto. Me parece que deberian haber dos tipos de "favoritos". Uno para tener a mano cosas y otro para fusión automática. Sino por ahí es demasiado. Les parece? Por ahora voy a dejar por defecto que se fusionen las subscripciones.
