### ISSUE TITLE
Agregar pantalla de inicio mientras se carga la web

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#18]

**Comment by fcladera** [comment]
Para esta issue, un plugin que puede ser bueno, bonito y barato (o liviano)

http://github.hubspot.com/pace/docs/welcome/

**Comment by andresmanelli** [comment]
Pace no funciona bien con AngularJS. Pero estoy trabajando en el splash. Ya casi está listo. También estoy agregando una progress bar (como la que sale en YouTube arriba).
