### ISSUE TITLE
Migrar Express 3.x a 4.x

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#22]
Express 3.x support is ending soon

This series will continue to receive only security updates and bug fixes until July 2015. It is highly recommended to upgrade to Express 4.x.

[Guía](http://expressjs.com/guide/migrating-4.html)

**Comment by francoa** [comment]
este va a estar jodido

**Comment by francoa** [comment]
Terminado en branch feature/expressMigration

**Comment by andresmanelli** [comment]
No habría que cerrarlo al mergear el pull request? Capo

**Comment by francoa** [comment]
En teoría sí pero tenía ganas de cerrar un issue. Lo abro de nuevo si te
jode.
No hice wl merge xq me parece que tenemos que hacerlo con el branch
organization (no?) y quería consultarte si estaba listo antes de hacerlo

**Comment by andresmanelli** [comment]
Jaja te lo permito porque andás con nariz nueva. Nada más.

No le voy a agregar nada más. Ya cambié lo de localhost. El resto te anduvo bien cierto? Dsp que lo pruebe Fer mergeamos.
