### ISSUE TITLE
Establecer Node v4 como la versión a utilizar

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#25]
Dejar dicho en el README y usar la versión LTS [v4](https://nodejs.org/en/)

**Comment by fcladera** [comment]
Upgrade upgrade!

**Comment by andresmanelli** [comment]
Estuve probando hoy con la última versión estable de node (v5.10) --cambiaron los números de versiones de manera increible jaja). Y anda perfecto. Hay que volver a instalar `node_modules` pero por lo demás anda. Asique alguno que pruebe tmb así cerramos esto.

**Comment by fcladera** [comment]
On Monday, April 4, 2016 6:48:54 PM ART Andr�s wrote:

> Assigned #25 to @fcladera.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/25#event-614
> 529488

ACK boss

**Comment by andresmanelli** [comment]
Faltó un `#` en el P.R. Closed via #130
