### ISSUE TITLE
Los repos de francoa y MecatronicaUncu no tienen nada que ver

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#28]
Es como si ambos repos tuviesen orígenes diferentes, o han hecho un rebase muy heavy, o algo. Cuando traten de hacer un pull request las cosas van a explotar!

Soluciones:
 * Que Franco borre su repo y clone este.
 * Que tratemos de encontrar un punto en común y hagamos un merge antes de que sea muy tarde.

**Comment by francoa** [comment]
fue un clone pero creando nuevo repositorio. Borro el mío total no está en
uso

2015-09-09 15:17 GMT-03:00 Fernando Cladera <notifications@github.com>:

**Comment by andresmanelli** [comment]
El de franco era el original, despues lo pasamos a la Asoc y seguimos ahí. Es posible que algo haya pasado. Pero no hay nada nuevo en el del H.H me parece. @francoa que opinas?

**Comment by fcladera** [comment]
Lo que va a pasar es que se va a perder la historia de commits. Pero es raro esto, de que hayan quedado como dos cosas independientes. Es como si no hubiesen transferido el repo, sino que lo hubiesen vuelto a subir.

**Comment by francoa** [comment]
No hay nada de nada nuevo. Borro y todo va a estar bien. Ya voy a tener
tiempo para ponerme a tocar esto la semana que viene

2015-09-09 15:21 GMT-03:00 Andrés <notifications@github.com>:

**Comment by francoa** [comment]
Probablemente hayamos creado un repo nuevo.

2015-09-09 15:23 GMT-03:00 Fernando Cladera <notifications@github.com>:

**Comment by fcladera** [comment]
On Wednesday, September 09, 2015 11:24:45 AM francoa wrote:
> Probablemente hayamos creado un repo nuevo.
> 
> 2015-09-09 15:23 GMT-03:00 Fernando Cladera <notifications@github.com>:
> > Lo que va a pasar es que se va a perder la historia de commits. Pero es
> > raro esto, de que hayan quedado como dos cosas independientes. Es como si
> > no hubiesen transferido el repo, sino que lo hubiesen vuelto a subir.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/28#issuec
> > omment-138997747> .
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/28#issuecomm
> ent-138998095

Genial. Hacé una copia por las dudas haha!

**Comment by francoa** [comment]
Fue un pull request lo que habíamos hecho

2015-09-09 15:26 GMT-03:00 Fernando Cladera <notifications@github.com>:

**Comment by francoa** [comment]
Listo el pollo

2015-09-09 15:28 GMT-03:00 Franco Ardiani <francoamg@gmail.com>:
