### ISSUE TITLE
Crear script para configurar la red social

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#29]
A configurar:
- [x] Acceso Web a Neo4J
- [x] Certificados SSL
- [x] user & pass (neo4j 2.2.5)
- [x] Nodo dummy
- [x] Constraint on email
- [x] Preguntar por host de conexión (LAN/Local/Internet)

Debería dejar la red lista para funcionar. (Branch feat-init-script)

**Comment by andresmanelli** [comment]
@fcladera podés mirar esto a ver qué te parece? No estoy muy seguro sobre el uso de sudo. 39e6d6e3c0b0bad9b7f2179201f9be0cea8e69d0

**Comment by fcladera** [comment]
No hay que usar sudo nunca. Si usás sudo es que estás haciendo algo mal.

**Comment by fcladera** [comment]
Ahora lo miro

**Comment by fcladera** [comment]
Ah, entiendo para que usás sudo...

Algo de lectura buena https://wiki.archlinux.org/index.php/Realtime_process_management

Creo que la solución pasa por leer el valor hard del sistema operativo, y ver si se puede incrementar en modo usuario. En caso de que no se pueda, lo mejor es que esta parte aparezca en la wiki como una lista de pasos. Por regla general, es mala idea que un script de usuario llame a sudo.

**Comment by fcladera** [comment]
http://neo4j.com/docs/stable/linux-performance-guide.html

Otra cosa que jode un poco, es que esa guía está escrita para Ubuntu. Creo que sería mejor dejarlo genérico en el README.md

**Comment by andresmanelli** [comment]
Dale, después lo arreglo.

**Comment by andresmanelli** [comment]
Terminado con 04714ef8c2f8864900c1ca2682530d7ff727c894
