### ISSUE TITLE
node-neo4j update

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#30]
Ya está la versión 2 del paquete node-neo4j, que es el que funciona con neo4j 2.2.x (y tengo entendido que con node 0.12).

[LINK](https://github.com/thingdom/node-neo4j/tree/v2)

Vamos a tener que cambiar algunas cosas me imagino.

**Comment by fcladera** [comment]
Una vez que esto esté, yo puedo deployar desde ubuntu 16.04

**Comment by andresmanelli** [comment]
Esto comentaron hace 7 días: " I've been thinking I should maybe just merge this PR in its current state, even without the docs finished, just to make it clear that v2 is production-ready. [...] "

Ya se puede ver de usarlo entonces.

**Comment by francoa** [comment]
on it
