### ISSUE TITLE
bower setup.sh

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#31]
bower install no se ejecuta en setup.sh

**Comment by fcladera** [comment]
bower install >> setup.log 2>&1

**Comment by andresmanelli** [comment]
Me parece que esto pasa por problema de dependencias. Si se ejecuta a mano sale el menu siguiente:

```
Unable to find a suitable version for angular, please choose one:
    1) angular#1.2.15 which resolved to 1.2.15 and is required by angular-mocks#1.2.15, angular-resource#1.2.15, angular-route#1.2.15, angular-scenario#1.2.15
    2) angular#1.2.16 which resolved to 1.2.16 and is required by angular-sanitize#1.2.16
    3) angular#~1.2.15 which resolved to 1.2.28 and is required by angular
    4) angular#1.2.28 which resolved to 1.2.28 and is required by angular-cookies#1.2.28
    5) angular#>=1 <1.3.0 which resolved to 1.2.28 and is required by angular-bootstrap#0.12.1
```

Si uno sale sin elegir nada, no se instala nada.

**Comment by francoa** [comment]
Perfecto, ahi veo de corregirlo

**Comment by francoa** [comment]
Les parece forzar la selección de versión a la más reciente?

**Comment by fcladera** [comment]
Creo que es mejor fijar una versión determinada. Así tenemos un poco de control de las cosas que se instalan.

**Comment by francoa** [comment]
Voy a fijar la versión 1.2.28 de angular en bower.json, pero de todas formas voy a forzar la selección de la versión más reciente para que el script no explote en el futuro. Angular fue el único que nos ha dado problemas de resolución

**Comment by andresmanelli** [comment]
Hay que abrir otro issue porque hay que limpiar bien Gruntfile y el package.json. Hay cosas en devDependencies que se usan en production. En general todo eso lo hicimos como pudimos y no quedó bien (me parece jaja)

**Comment by francoa** [comment]
bueno hago merge a develop y abrimos otro issue con eso
