### ISSUE TITLE
Organización de branchs

### ISSUE THREAD

**Issue by francoa** [MecatronicaUncu/Red-Social-Asociacion#34]
Ahora que somos varios trabajando sobre lo mismo (y a distancia), estaría bueno que nos pongamos de acuerdo en la forma de organizarnos. 

Propongo una organización de branches que en el laburo nos es muy útil:
1- El master no se toca. Se deja en una versión funcional y sólo se hace merge a este branch cuando se tenga un "entregable".
2- Se hace un branch develop. En ese branch van todos los cambios. Sin embargo, tampoco se cambian muchas cosas SOBRE develop.
3- En cambio, para agregar modificaciones se abren nuevos branch de develop con nombres explicativos del "feature" que implementan. De hecho, está bueno si a esos branch les ponemos "feature/nombreExplicativo", porque así algunos programas hacen una organización de árbol que puede ser útil.
4- Cuando se termina y testea el feature se hace merge request a develop.

**Comment by andresmanelli** [comment]
Cómo siguen los puntos? Quiero decir, 
- Quién autoriza el merge a develop?
- Cuándo se hace el merge a master desde develop? Cómo se cordina?

**Comment by francoa** [comment]
Cuando creas un merge request creo que podés asignarselo a alguien(es). Ese alguien(es) estaría encargado de autorizar el merge. Calculo que a nosotros no nos haría falta, pero está bueno para el caso en que hayan conflictos, en ese caso el merge request falla y hay que hacer merge manual, en el cual tienen que participar todos aquellos que hayan hecho cambios que puedan ser borrados.

El merge a master se hace cada bastante. Por lo general el master se deja como salvaguarda. Se hace un merge request desde develop hacia master y participan todos.

**Comment by fcladera** [comment]
On September 15, 2015 7:14:08 PM GMT-03:00, francoa notifications@github.com wrote:

> Cuando creas un merge request creo que podés asignarselo a alguien(es).
> Ese alguien(es) estaría encargado de autorizar el merge. Calculo que a
> nosotros no nos haría falta, pero está bueno para el caso en que hayan
> conflictos, en ese caso el merge request falla y hay que hacer merge
> manual, en el cual tienen que participar todos aquellos que hayan hecho
> cambios que puedan ser borrados.
> 
> El merge a master se hace cada bastante. Por lo general el master se
> deja como salvaguarda. Se hace un merge request desde develop hacia
> master y participan todos.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/34#issuecomment-140561437

https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows

Depende del workflow que tengamos. Una buena lectura.

**Comment by francoa** [comment]
Sería una buena idea setear develop como el branch por default?

**Comment by andresmanelli** [comment]
@fcladera algun comentario ?

**Comment by fcladera** [comment]
Creo que @francoa es un buen mergeador de cosas, tiene pinta de que le gusta probar de todo a ver que es lo que mejor funciona.

**Comment by francoa** [comment]
jajajaja no sé si habla bien de mi eso de que me gusta probar de todo.

Lo q me jode de que develop no sea el default es que si hacés un pull request con "Fixes #xx" no te cierra el issue

**Comment by andresmanelli** [comment]
Si te parece que va a ser util dale para adelante. Probalo. Tal vez te guste jaja. Yo te sigo a todos lados

**Comment by fcladera** [comment]
Que sea entonces!

**Comment by francoa** [comment]
joya, realizado. Ahora con los pull request deberían poder cerrar issues

**Comment by francoa** [comment]
además cuando hagan clone, va a descargar el develop y todos los pull request van a ir a ese branch por defecto

**Comment by fcladera** [comment]
Creo que esto ya está, lo cierro
