### ISSUE TITLE
Preparar el proyecto para un desarrollo open source

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#37]
Flint es una herramienta que _Check your project for common sources of contributor friction._

https://github.com/pengwynn/flint

Estaría bueno corregir los errores que marca en nuestro repo. Lo acabo de correr y da lo siguiente

[ERROR] CONTRIBUTING guide not found
[INFO] Add a guide for potential contributors. http://git.io/z-TiGg
[ERROR] LICENSE not found
[INFO] Add a license to protect yourself and your users. http://choosealicense.com/
[WARNING] Bootstrap script not found
[INFO] A bootstrap script makes setup a snap. http://bit.ly/JZjVL6
[WARNING] Test script not found
[INFO] Make it easy to run the test suite regardless of project type. http://bit.ly/JZjVL6

El bootstrap script sería nuestro setup.sh, esa es fácil de solucionar (cambio de nombre).
Licencia?
Test script?
- [x] LICENSE
- [x] CONTRIBUTING
- [x] Bootstrap script: `bootstrap` folder: `setup` + `config` (Verificar)
- [x] Test script: `npm test` a.k.a `grunt build` (Para nada completo pero ahí está)

**Comment by fcladera** [comment]
Para este caso, creo que lo mejor es la licencia GPL v2 o v3

**Comment by andresmanelli** [comment]
Los tests van a ser lo más complicado. Personalmente hice un poco de TDD en Node pero no tengo idea para hacer los tests de HTTP requests y del funcionamiento general de la red social. Tema para investigar..

Pregunta: Para testear en sandbox los scripts (config y setup por ahora), se podrá hacer desde un CI como Travis?

**Comment by fcladera** [comment]
Alguien ha usado Travis ya?

**Comment by andresmanelli** [comment]
Muy informalmente. No con workflow pro. Igual mas alla de travis lo importante no es el motor de tests que se use?

**Comment by fcladera** [comment]
On September 20, 2015 5:13:41 PM GMT-03:00, "Andrés" notifications@github.com wrote:

> Muy informalmente. No con workflow pro. Igual mas alla de travis lo
> importante no es el motor de tests que se use?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/37#issuecomment-141829584

No lo sé. Ustedes son los pibes javascript :-D

**Comment by andresmanelli** [comment]
Jaja pero en general digo. Los CI lo unico que hacen es recibir un push y ejecutar comandos. A eso iba. Saber usarlo no significa saber usar un Framework de tests de JS
