### ISSUE TITLE
Travis falló el build después de merge a develop

### ISSUE THREAD

**Issue by francoa** [MecatronicaUncu/Red-Social-Asociacion#41]
![screenshot](https://cloud.githubusercontent.com/assets/7302227/9983231/c8dc38a6-5fcb-11e5-85d5-49d8db166bb3.png)

**Comment by fcladera** [comment]
Alguna vez lo hizo? EL problema es que no hay un Rakefile, pero no sé si su proyecto lo usa. Nosotros escribimos el equivalente mexicano en el setup.sh.

Estuve viendo un poco de este muchacho Travis, parece que hay que escribir un .travis.yml que haga todo.

**Comment by andresmanelli** [comment]
Hay que hacer el .travis.yml. algo como:

language: node_js
node_js:
- "0.10"
  before_install:
- npm install -g grunt-cli
  notifications:
  email: false

se ejecuta lo que está en package.json como test creo, que seria:

grunt test en nuestro caso, pero hay que ver el Gruntfile.

**Comment by andresmanelli** [comment]
Se activa el build con push a develop?

**Comment by francoa** [comment]
si, así parece. Corregí directamente en develop si no es un cambio grande

**Comment by andresmanelli** [comment]
Ok

**Comment by andresmanelli** [comment]
Si agregás la status image al README? [aca](http://docs.travis-ci.com/user/status-images/)

**Comment by andresmanelli** [comment]
Me podés pasar el link al build de travis?

**Comment by francoa** [comment]
si perdón. Anda a la página principal del proyecto, clickeá sobre branches y después en la cruz roja donde dice que falló el build. 

El link es https://travis-ci.org/MecatronicaUncu/Red-Social-Asociacion/builds/81301994

**Comment by andresmanelli** [comment]
Voy a hacer commits desmesurados a develop si te parece hasta que ande la parte de setup y config.

**Comment by francoa** [comment]
Ok, aceptame el pull request así tenes los cambios de mi branch (que son mínimos porque ya hiciste checkout) y dale. Si se van a zarpar en desmesurados los commits tal vez convenga hacer branch, elegí lo que te parezca más conveniente

**Comment by andresmanelli** [comment]
Ahi hace perfecto setup.sh desde travis. Bien Franco !! La parte de config hay que modificar porque espera un enter después de iniciar neo, no sabria bien como manejar eso, voy a probar en un branch mejor. Tuviste que agregar a mano que el branch ejecute el build o se hace solo?

**Comment by francoa** [comment]
No hice nada, se hizo todo sólo

**Comment by andresmanelli** [comment]
Cerrado con el PR #46!
