### ISSUE TITLE
setup.sh trata de instalar yo, n4j y bower globalmente

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#42]
Acá tengo una duda, por qué lo tratan de instalar globalmente? No corresponde hacerlo por usuario?
En mi caso, setup.sh falló porque no tenía permisos para escribir en la carpeta de npm (en /usr).

**Comment by andresmanelli** [comment]
Si instalaste node con node version manager, te instala todo por usuario. Global significa que no pertenece a ese proyecto en particular sino que lo tenes disponible para cualquier proyecto. 

Los permisos se solucionan si instalás bien NVM (con bien quiero decir, como usuario, no como root)

**Comment by fcladera** [comment]
Ok, entiendo y puede que tenga los permisos rotos en algún lado. Además de que se puede usar para otro proyecto, qué ventaja tiene hacerlo global?

**Comment by fcladera** [comment]
En mi caso, manualmente puedo instalar como global pero falla el script. Supongo que tiene algo que ver con que los path no están seteados en bash pero si en zsh.

**Comment by andresmanelli** [comment]
por ejemplo, grunt-cli se instala global para tener el comando `grunt` desde la terminal (y ejecuta la version local instalada). lo mismo para bower y yo. Yeoman es para crear proyectos, no podrias crear un proyecto si no fuese global.. o te meteria el package en tu proyecto, y en realidad no forma parte del proyecto en si, es una herramienta para generar el esqueleto.

**Comment by fcladera** [comment]
Ok para grunt y para yo, ya los he usado también yo para mi página y algo pude aprender al respecto. Ahora bien, es igual para neo4j que es específico a este proyecto? 
Otra pregunta también sin saber mucho, para qué se sigue usando yo si el proyecto ya está _scaffolded_?

**Comment by andresmanelli** [comment]
Tenés razon ahi, ese no hay que instalarlo para que ande. Querés cerrarlo cambiando eso directamente a develop?
- neo4j local
- sacar yo

@francoa te parece?

**Comment by fcladera** [comment]
On Sunday, September 20, 2015 04:21:42 PM Andrés wrote:

> Tenés razon ahi, ese no hay que instalarlo para que ande. Querés cerrarlo
> cambiando eso directamente a develop? - neo4j local
> - sacar yo
>   @francoa te parece?

Yo me encargo Willis.

**Comment by francoa** [comment]
De acuerdo con ambas
