### ISSUE TITLE
Borrar ramas que ya no se usen

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#47]
Una vez que ciertas features van a develop, deberíamos borrar las ramas viejas. Así no hacen tanto ruido en el repo.

**Comment by andresmanelli** [comment]
dejá de abrir issues. Cerrá algunos jaja

**Comment by fcladera** [comment]
On Monday, September 21, 2015 07:12:42 AM Andrés wrote:

> dejá de abrir issues jaja

Los issues hacen grande a este país. Además te cerré uno antes, así la
bandeja se equilibra.

**Comment by fcladera** [comment]
Ahora te voy a abrir un pr, para que veas.

**Comment by francoa** [comment]
OK.

A veces las ramas se dejan para poder hacer un seguimiento de las tareas realizadas por cada uno, pero como eso no nos interesa las borramos.
