### ISSUE TITLE
Versión dev para hacer beta tests

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#5]
Cuando se pueda, estaría bueno correr una versión de prueba en el server, a lo sumo protegida con contraseña, para que la gente ociosa pueda cazar bugs y reportarlos.

**Comment by fcladera** [comment]
Novedades (el que venía a exigir haha, últimamente me han llegado mails de movimiento en el proyecto)

**Comment by andresmanelli** [comment]
Ahi está corriendo Fer, te invito a registrarte !

(https://edt.mecatronicauncu.org:3000)
