### ISSUE TITLE
Instalar node-neo4j con package.json

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#50]
Por alguna razón instalamos node-neo4j en setup.sh y no lo hacemos mediante package.json?

**Comment by andresmanelli** [comment]
La verdad que en este momento no sé pero me gusta que no hayas dejado el barco jaja

**Comment by fcladera** [comment]
Digamos que es un hobby, que no creo que vaya a cambiar al mundo, pero me trae paz. Es como tener el pasto cortado en el jardín.

**Comment by fcladera** [comment]
fvim va a cambiar al mundo
(tampoco creo que vaya a cambiar al mundo)

**Comment by andresmanelli** [comment]
@fcladera podrías hacer un PR para agreguarlo al `package.json` ?

**Comment by fcladera** [comment]
Ahora, creo que lo mejor va a ser instalar esto con un .deb

**Comment by fcladera** [comment]
Cierro esto porque no tiene mucha relevancia.
