### ISSUE TITLE
Organización 

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#52]
Les parece que re-estructuremos todo usando [ng-boilerplate](https://github.com/ngbp/ngbp)? Parece que es muy muy recomendado para que sea escalable el proyecto. Sobre todo porque entre tanto toqueteo el Gruntfile está medio sucio me parece y no estaría mal ahora que estamos trabajando, que las cosas estén ordenadas.

Si le sparece, lo hacemos, pero hay que frenar las ediciones hasta tener esto hecho porque sino van a haber varios problemas supongo. Y calculo que lo que vamos a tener que revisar bien es el nuevo Gruntfile.js para que quede todo andando.

El boilerplate viene con determinadas bibliotecas, habría que tocar un poquito las cosas para sacar lo que no haga falta.

Bueno, qué dicen?

**Comment by fcladera** [comment]
Estaría bueno!
