### ISSUE TITLE
Mail de activacion

### ISSUE THREAD

**Issue by francoa** [MecatronicaUncu/Red-Social-Asociacion#64]
- [x] Se envían dos mails.
- [x] La dirección de activación está mal.
- [x] Rehacer el template al que direcciona el mail.

**Comment by andresmanelli** [comment]
ya que @francoa está activado le voy a dar trabajo jaja

**Comment by francoa** [comment]
@andresmanelli 

Para que tengamos en cuenta en un futuro. El signup devuelve siempre 200 una vez que inicia el proceso de envío de mail de activación. Tendríamos que contemplar la posibilidad de que el email no se mande, y permitir en el frontend una opción "reenviar mail de activación", como suele existir en muchas páginas.

**Comment by francoa** [comment]
![image](https://cloud.githubusercontent.com/assets/7302227/13835732/98ac6db4-ebd9-11e5-9ee0-1f0f2d96b31a.png)

**Comment by francoa** [comment]
Un preview del mail que se está mandando ahora

**Comment by andresmanelli** [comment]
Me encantó. Lo del link para reenviar si, claro. Debería estar. Una pregunta:
- Porqué lo de activación sale debajo de los [...] ?

**Comment by francoa** [comment]
Es que antes de ese mail hubieron 7 que salieron en prueba. Gmail los agrupa y hace como que son reenvíos porque el contenido es el mismo

**Comment by andresmanelli** [comment]
Roger that. Quedó muy bien.

**Comment by francoa** [comment]
![image](https://cloud.githubusercontent.com/assets/7302227/13836167/46dbd1c4-ebdd-11e5-9a1f-2d58bc6490b2.png)

**Comment by francoa** [comment]
Quieren algo más de chimi ahi?

**Comment by andresmanelli** [comment]
Por mí está bien.
