### ISSUE TITLE
CORS headers on server

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#77]
Parece que usando esto se soluciona el tema de los errores CORS.

@francoa o @fcladera pueden hacer una prueba?

Se podría eliminar el paso de `config` de eleccion de host.

Gracias @fcladera 

Ver: [express/cors](https://github.com/expressjs/cors)

**Comment by francoa** [comment]
En qué branch? Alguna vez lo probé pero en la versión vieja de express y no hacía gran diferencia

**Comment by andresmanelli** [comment]
Si queres hacé la v-0.1 a partir de develop y arrancamos a tirar P.R hacia esa. A eso te referís?

-----Message d'origine-----
De : "Franco Ardiani" notifications@github.com
Envoyé : ‎14/‎03/‎2016 19:24
À : "MecatronicaUncu/Red-Social-Asociacion" Red-Social-Asociacion@noreply.github.com
Cc : "Andrés" andresmanelli@gmail.com
Objet : Re: [Red-Social-Asociacion] CORS headers on server (#77)

En qué branch? Alguna vez lo probé pero en la versión vieja de express y no hacía gran diferencia

**Comment by francoa** [comment]
No, es que pensé que ya habías abierto branch para tratar esto.

Dicho sea de paso, esto:
`var allowCrossDomain = function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "https://127.0.0.1:3000");
    //res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    res.header("Access-Control-Allow-Headers", "Content-Type, Accept, X-Requested-With");
    //res.header("Access-Control-Allow-Headers", "DNT, X-Mx-ReqToken, Keep-Alive, User-Agent, If-Modified-Since, Cache-Control, Origin, X-Requested-With, Content-Type,Accept,Authorization,X-HTTP-Method-Override");
    res.header('Access-Control-Allow-Credentials', true);
    res.header('Access-Control-Max-Age', 3600);
    next();
};`
se supone que es algo así como cors, pero nunca supe si funciona muy bien la verdad

**Comment by francoa** [comment]
creo que ya lo tengo, aguantenme

**Comment by francoa** [comment]
A alguno se le ocurre una forma de probar esto?

**Comment by francoa** [comment]
Bueno, fíjense si lo encuentran bien solucionado. Es el branch feature/77-CORS

Puse un WhiteList de URLs que pueden hacer c-o domain requests en server.js, para mantener control.

http://www.html5rocks.com/en/tutorials/cors/

**Comment by andresmanelli** [comment]
Anda para el caso app configurado con LAN IP y acceder desde localhost, pero no en sentido contrario. Esto en realidad es un problema de desarrollo. A la hora de tener el nombre de dominio se soluciona.

Podemos dejar como opciones en `./bootstrap/config` el caso de LAN y NET, porque como ese IP varía, no podemos configurar el cors del server cada vez, no vale la pena. Les parece?

Sino, el script de config debería agregar a `server.js` la LAN IP en la white list.

**Comment by fcladera** [comment]
On Tuesday, March 15, 2016 12:23:11 PM ART, Andrés wrote:

> Anda para el caso app configurado con LAN IP y acceder desde 
> localhost, pero no en sentido contrario. Esto en realidad es un 
> problema de desarrollo. A la hora de tener el nombre de dominio 
> se soluciona.
> 
> Podemos dejar como opciones en `./bootstrap/config` el caso de 
> LAN y NET, porque como ese IP varía, no podemos configurar el 
> cors del server cada vez, no vale la pena. Les parece?

No me sigue cerrando este problema. Si vos querés distribuir tu programa, 
el servicio debería ser agnóstico del lugar donde está instalado (no sé si 
agnóstico es la palabra indicada, haha). Pero no te molesto más Rulo!

**Comment by francoa** [comment]
Bueno esto se solucionaría (en teoría) poniendo `'*'` en la lista de dominios permitidos. Pero me parece que con eso debilitas el server no?

**Comment by fcladera** [comment]
On Tuesday, March 15, 2016 3:38:02 PM ART, Franco Ardiani wrote:

> Bueno esto se solucionaría (en teoría) poniendo `'*'` en la 
> lista de dominios permitidos. Pero me parece que con eso 
> debilitas el server no?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/77#issuecomment-196966406

who cares, estamos en dev. Después a la hora de hacer las cosas bien, las 
hacemos bien.

**Comment by francoa** [comment]
Fuck yeah

**Comment by andresmanelli** [comment]
El problema está en la diferencia entre lo que dice la barra del navegador y a donde hacés las requests desde javascript del front end. Claro (creo) que se puede poner un \* si tuvieses contenido accesible para todos en una route en particular (como un cdn) pero otra cosa es por ejemplo, hacer un login desde otro dominio.

Por eso digo que si trabajaramos con un dominio propio, no tendriamos problema.  No se si es lo mejor poner \* en todos lados. Yo lo dejaria por ahora como hizo Franco, sacando la opcion localhost de config.

-----Message d'origine-----
De : "Franco Ardiani" notifications@github.com
Envoyé : ‎15/‎03/‎2016 15:38
À : "MecatronicaUncu/Red-Social-Asociacion" Red-Social-Asociacion@noreply.github.com
Cc : "Andrés" andresmanelli@gmail.com
Objet : Re: [Red-Social-Asociacion] CORS headers on server (#77)

Bueno esto se solucionaría (en teoría) poniendo '*' en la lista de dominios permitidos. Pero me parece que con eso debilitas el server no?

**Comment by francoa** [comment]
I'm on it. Se viene el PR

**Comment by francoa** [comment]
che igual lo que me ha dado hasta ahora problemas no es el cross-domain sino el certificado

**Comment by andresmanelli** [comment]
Es que es self signed. Eso va a ser asi hasta que paguemos uno en serio

-----Message d'origine-----
De : "Franco Ardiani" notifications@github.com
Envoyé : ‎15/‎03/‎2016 16:26
À : "MecatronicaUncu/Red-Social-Asociacion" Red-Social-Asociacion@noreply.github.com
Cc : "Andrés" andresmanelli@gmail.com
Objet : Re: [Red-Social-Asociacion] CORS headers on server (#77)

che igual lo que me ha dado hasta ahora problemas no es el cross-domain sino el certificado

**Comment by fcladera** [comment]
On Tuesday, March 15, 2016 4:30:01 PM ART, Andrés wrote:

> Es que es self signed. Eso va a ser asi hasta que paguemos uno en serio

Yo le dije al Rulo esto ayer, si el problema era el ssl. Tiene lógica que 
para hacer un certificado tengamos que especificar el dominio.
