### ISSUE TITLE
La dama está gorda

### ISSUE THREAD

**Issue by fcladera** [MecatronicaUncu/Red-Social-Asociacion#78]
Estoy tratando de hacer un container con docker, y el proyecto completo pesa 1.5 GB! De más está decir que es gordo, muy gordo. Hay que limpiar (y actualizar la doc y los scripts de instalación avec). 
Si alguien tiene una idea de cosa que esté extra, puede agregarla a este thread.
Ej:
MONGO

**Comment by fcladera** [comment]
Usar la última versión de node, ideas @andresmanelli ?

**Comment by fcladera** [comment]
Usar sólo curl, y no usar wget

**Comment by fcladera** [comment]
Ruby es necesario usar rvm? No podemos usar una versión de paquete de una distro?

**Comment by andresmanelli** [comment]
- Dependencias out-of-date de `package.json` (y su versión más reciente):
```
 email-templates                  ^1.2.0  →    ^2.2.0 
 grunt-contrib-sass               ^0.8.1  →    ^1.0.0 
 mongodb                         ^1.4.19  →    ^2.1.8 
 neo4j                              ~1.1  →  ~2.0-RC2 
 nodemailer                       ~0.7.1  →    ~2.3.0 
 cookies                          ^0.5.0  →    ^0.6.1 
 grunt-autoprefixer               ~0.4.0  →    ~3.0.4 
 grunt-bower-install              ~1.0.0  →    ~1.6.0 
 grunt-bump                        0.0.6  →     0.7.0 
 grunt-concurrent                 ~0.5.0  →    ~2.2.1 
 grunt-contrib-clean              ~0.5.0  →    ~1.0.0 
 grunt-contrib-coffee             ^0.7.0  →    ^1.0.0 
 grunt-contrib-concat             ~0.3.0  →    ~1.0.0 
 grunt-contrib-connect            ~0.5.0  →    ~1.0.0 
 grunt-contrib-copy               ~0.4.1  →    ~1.0.0 
 grunt-contrib-cssmin             ~0.7.0  →    ~1.0.0 
 grunt-contrib-htmlmin            ~0.1.3  →    ~1.0.0 
 grunt-contrib-imagemin           ~0.3.0  →    ~1.0.0 
 grunt-contrib-jshint             ~0.7.1  →    ~1.0.0 
 grunt-contrib-uglify             ~0.2.0  →    ~1.0.0 
 grunt-contrib-watch              ~0.5.2  →    ~1.0.0 
 grunt-conventional-changelog     ^0.1.2  →    ^6.1.0 
 grunt-develop                    ~0.2.2  →    ~0.4.0 
 grunt-google-cdn                 ~0.2.0  →    ~0.4.3 
 grunt-html2js                    ^0.1.9  →    ^0.3.5 
 grunt-karma                      ^0.8.3  →   ^0.12.1 
 grunt-newer                      ~0.6.1  →    ~1.1.2 
 grunt-ng-annotate               ^0.10.0  →    ^2.0.1 
 grunt-svgmin                     ~0.2.0  →    ~3.1.2 
 grunt-usemin                     ~2.0.0  →    ~3.1.1 
 jshint-stylish                   ~0.1.3  →    ~2.1.0 
 karma                          ^0.12.16  →  ^0.13.22 
 karma-coffee-preprocessor        ^0.2.1  →    ^0.3.0 
 karma-mocha-reporter             ^1.1.3  →    ^2.0.0 
 karma-ng-html2js-preprocessor    ^0.1.0  →    ^0.2.1 
 load-grunt-tasks                 ~0.4.0  →    ~3.4.1 
 request                         ~2.27.0  →   ~2.69.0 
 sha256                           ^0.1.1  →    ^0.2.0 
 time-grunt                       ~0.2.1  →    ~1.3.0
```

Dependencias out-of-date de `bower.json` (y su versión más reciente):

```
 angular             1.2.28  →   1.5.0 
 angular-bootstrap  ~0.12.1  →  ~1.2.4 
 angular-cookies    ~1.2.17  →  ~1.5.0 
 angular-resource    1.2.15  →   1.5.0 
 angular-sanitize    1.2.16  →   1.5.0 
 bootstrap           ~3.0.3  →  ~3.3.6 
 es5-shim            ~2.1.0  →  ~4.5.7 
 font-awesome        ~4.3.0  →  ~4.5.0 
 jquery              ~2.1.4  →  ~2.2.1 
 json3               ~3.2.6  →  ~3.3.2 
 parsleyjs           ~2.0.5  →  ~2.3.5 
 angular-mocks       1.2.15  →   1.5.0 
 angular-scenario    1.2.15  →   1.5.0
```

**Comment by fcladera** [comment]
Lo que he pensado para esto es lo siguiente: vamos a pegarnos a la versión LTS de Ubuntu, para los paquetes grandes. Las LTS son versiones con soporte para actualizaciones de seguridad, pero no cambian las versiones de los paquetes individuales. Esto es ideal, porque podemos tener un entorno de desarrollo común donde las cosas funcionen para todos, y que habría que actualizar cada vez que salga una nueva LTS, cada dos años.
- npm 1.3.10
- nodejs 0.10.25
- git 1.9.1
- ruby 1.9.3
- jre 1.7

Neo4j parece que no tiene paquete oficial para ubuntu, por lo que deberíamos tratar de fijar una versión en particular que no joda con las dependencias que tenemos ahora.

Para las otras dependencias que se manejan con npm o bower, el control de versiones se hace efectivamente en el programa, porque no habría problema.

Qué les parece? Comentarios?

**Comment by andresmanelli** [comment]
El tema de nodejs, fijate que hay versiones mucho mas nuevas y que de hecho creo que la 0.10 o 0.12 van a salir de circulación. Copio: v4.4.0 For most users y v5.8.0 stable With latest features. Yo estoy usando la stable sin ningún problema.

Ruby ya está en la 2.3.0 (que la uso ahora sin problemas también).

Git no estoy seguro ahroa pero en la página figura la 2.7.3 (Por algo en especial pusiste la 1.9.3?)

jre ni idea.

Pregunto de paso: Se puede hacer un docker file para automatic deployment? No tengo ni idea como es todo ese proceso pero estaria bueno ir pensandolo.

**Comment by fcladera** [comment]
Podemos pegarnos a una versión de ubuntu más reciente, si queremos tener paquetes más nuevos. El problema de eso es que hay que estar actualizando cada 9 meses, porque las versiones pierden soporte (por eso había propuesto lo de LTS). Pero no es una mala idea!

En teoría, una vez que el container está hecho (por Dockerfile o por commits sobre un container), uno puede hacer deploy con el container. Es la magia de todo esto :)

**Comment by fcladera** [comment]
A ver si esta te gusta Rulo:
- npm 3.5.2
- nodejs 4.2.6
- git 2.7.0
- ruby 2.3.0
- jre 1.8

**Comment by andresmanelli** [comment]
Go for it

-----Message d'origine-----
De : "Fernando Cladera" notifications@github.com
Envoyé : ‎15/‎03/‎2016 21:04
À : "MecatronicaUncu/Red-Social-Asociacion" Red-Social-Asociacion@noreply.github.com
Cc : "Andrés" andresmanelli@gmail.com
Objet : Re: [Red-Social-Asociacion] La dama está gorda (#78)

A ver si esta te gusta Rulo:
npm 3.5.2 
nodejs 4.2.6 
git 2.7.0 
ruby 2.3.0 
jre 1.8

**Comment by fcladera** [comment]
Hay que revisar si el jdk y el jre son necesarios en el Dockerfile. Es la última dependencia que nos queda por definir.

**Comment by fcladera** [comment]
Cierro esto porque no hay mucho más para sacar
