### ISSUE TITLE
Config options

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#86]
Franco fijate que cuando mergeaste el PR cambiando `config`, se rompió travis. en el .travis.yml quedó el argumento `LOC`. Tendrias que poner `LAN` como para que pase.

**Comment by andresmanelli** [comment]
Perdón, travis no se rompió, aunque debería. Lo del LOC a LAN sigue en pie.

Tal vez con los argumentos que está poniendo @fcladera esto se solucione

**Comment by francoa** [comment]
Lo corregí en el PR de mail activacion para no hacer un branch nuevo
