### ISSUE TITLE
Resolver REMOTE en tiempo de ejecución

### ISSUE THREAD

**Issue by andresmanelli** [MecatronicaUncu/Red-Social-Asociacion#89]
@fcladera suggested that `REMOTE` in `src/app/app.js` debería resolverse en runtime y que la elección de LAN o NET en `bootstrap/config` sea solo para el certificado self-signed SSL.

**Comment by andresmanelli** [comment]
Estuve probando, parece ser que somos unos tontos jaja. Directamente eliminando `REMOTE` (lo puse como '') todo se referencia al dominio actual, y plus de problèmes.

**Comment by fcladera** [comment]
On Monday, March 21, 2016 10:23:59 AM ART, Andrés wrote:

> Estuve probando, parece ser que somos unos tontos jaja. 
> Directamente eliminando `REMOTE` (lo puse como '') todo se 
> referencia al dominio actual, y plus de problèmes. 

Que bello es cuando las cosas son simples.
